INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'TlnKR kojulaenutus', 'Estonia pst 8, 15044 Tallinn (Kesklinn)', '6830920');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'TlnKR lastekirjandus', 'Estonia pst 8, 15044 Tallinn (Kesklinn)', '6830914');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Kadrioru', 'L. Koidula 12a, 10125 Tallinn (Kesklinn)', '6013420');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Kalamaja', 'Kotzebue 9, 10412 Tallinn (Põhja-Tallinn)', '6830970');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Kännukuke', 'E. Vilde tee 72, 12913 Tallinn (Mustamäe)', '6830951');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Laagna', 'Võru 11, 13612 Tallinn (Lasnamäe)', '6350020');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Männi', 'Ehitajate tee 48, 12612 Tallinn (Mustamäe)', '6532556');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Männiku', 'Pihlaka 12, 11211 Tallinn (Nõmme)', '6559718');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Nurmenuku', 'Ehitajate tee 109a, 13515 Tallinn (Haabersti)', '6830980');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Nõmme', 'Raudtee 68, 11618 Tallinn (Nõmme)', '6723858');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Paepealse', 'P. Pinna 8, 13615 Tallinn (Lasnamäe)', '6327463');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Pelguranna', 'Kangru 13, 10312 Tallinn (Põhja-Tallinn)', '6830931');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Pirita', 'Metsavahi tee 19, 11911 Tallinn (Pirita)', '6830955');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Pääsküla', 'Pärnu mnt 480a, 10913 Tallinn (Nõmme)', '6803495');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Sõle', 'Sõle 47b, 10321 Tallinn (Põhja-Tallinn)', '6019153');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Sääse', 'Sõpruse pst 186, 13424 Tallinn (Mustamäe)', '6830990');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Tondi', 'Pärnu mnt 125, 11314 Tallinn (Kesklinn)', '6748647');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Torupilli', 'Gonsiori 36, 10128 Tallinn (Kesklinn)', '6009113');
INSERT INTO library (id, name, address, contact) VALUES (nextval('hibernate_sequence'), 'Väike-Õismäe', 'Õismäe tee 115a, 13515 Tallinn (Haabersti)', '6740933');
